name: My CI/CD Pipeline

# The Event
on:
  push:
    branches:
      - main

# The Jobs
jobs:
  build:
    runs-on: ubuntu-latest

    # The Steps
    steps:
      # Step 0: Pull down your repository code
      - name: Fetch Codebase
        uses: actions/checkout@v4

      - name: Show current directory
        run: pwd

      - name: List files
        run: ls -la

      - name: Make directory
        run: mkdir my_new_directory

      - name: Echo statement
        run: echo " I am learning Github Actions"
